[package]
name = "pywebview"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
webview-app = { path = "../../../../lib/webview-app" }
