[package]
name = "pycopytrace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-runtime = { path = "../../../../lib/async-runtime" }
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
configmodel = { path = "../../../../lib/config/model" }
copytrace = { path = "../../../../lib/copytrace" }
dag = { path = "../../../../lib/dag" }
storemodel = { path = "../../../../lib/storemodel" }
types = { path = "../../../../lib/types" }
parking_lot = "0.12.1"
pymanifest = { path = "../pymanifest" }
