[package]
name = "pymetalog"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext" }
parking_lot = "0.12.1"
metalog = { path = "../../../../lib/metalog" }
