[package]
name = "pypathmatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
pathmatcher = { path = "../../../../lib/pathmatcher" }
tracing = "0.1.35"
types = { path = "../../../../lib/types" }
