[package]
name = "pydag"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.20"
async-runtime = { path = "../../../../lib/async-runtime" }
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
dag = { path = "../../../../lib/dag", features = ["render"] }
futures = { version = "0.3" }
hgcommits = { path = "../../../../lib/hgcommits" }
minibytes = { path = "../../../../lib/minibytes" }
parking_lot = "0.12.1"
pyedenapi = { path = "../pyedenapi" }
pymetalog = { path = "../pymetalog" }
storemodel = { path = "../../../../lib/storemodel" }
