[package]
name = "pymanifest"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.20"
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
manifest = { path = "../../../../lib/manifest" }
manifest-tree = { path = "../../../../lib/manifest-tree" }
parking_lot = "0.12.1"
pathmatcher = { path = "../../../../lib/pathmatcher" }
pypathmatcher = { path = "../pypathmatcher" }
types = { path = "../../../../lib/types" }
